version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: "mongodb+srv://hugiason16:fuUMUwp8H1HTkitC@mongo.c0lwj.mongodb.net/mbmFoodData?retryWrites=true&w=majority"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3002:3002"
    depends_on:
      - backend
    restart: unless-stopped
